### ISSUE TITLE
Changing world age in Communitu also changes resource settings

### ISSUE THREAD

**Issue by Zeodex** [LoneGazebo/Community-Patch-DLL#11728]
Changing the world age in Communitu automatically switches several other resource settings, and switching back the resource settings also reverses the world age. This happens immediately when changing the setting in multiplayer, but also seems to occur in singleplayer, as updating the game pace also switches the resources and starting a game with a different world age changes the default resource setting for the next game.

https://github.com/user-attachments/assets/2af542da-4642-454d-b369-d34d8e23da72

https://github.com/user-attachments/assets/27c3f527-8d78-4c37-a2c8-7f22af7340d6

**Comment by Zeodex** [comment]
Hi @axatin, this issue still persists for me with the latest map script.

**Comment by axatin** [comment]
It works fine for me. Are you sure you're not using an older copy of the map (Are you using a modpack, and did you manually copy the map to the Maps folder)?

I just realized I didn't update the version number when I fixed the bug. To be sure it's actually the newest version, use the file below, the version number in the map selection screen must be 3.1.1.

[Communitu_79a.zip](https://github.com/user-attachments/files/21209678/Communitu_79a.zip)

**Comment by Zeodex** [comment]
Yes, I am still having the bug with the file above.  The settings don't seem to immediately change anymore when changing the world age, but changing settings like the map size or game pace after changing the world age results in the same bug.
