### ISSUE TITLE
Cannot enhance religion whose Holy City has been captured

### ISSUE THREAD

**Issue by hkpuipui99** [LoneGazebo/Community-Patch-DLL#1517]
I captured Persepolis, holy city of Zoroastrianism, and wiped out the Persians completely.

However, they did not enhance the religion before they were ended.

When I got a Great Prophet, the tooltip said "Japanese Great Prophet Zoroastrianism", and there's a button to enhance religion. However, when I click on it, even though the enhance religion button pop up on the lower right, when you click into it, it takes you to the religion selection screen as if establishing a new religion. But it wouldn't let you establish a new religion either.

**Comment by LoneGazebo** [comment]
Which version of the mod?

**Comment by hkpuipui99** [comment]
V.72

**Comment by LoneGazebo** [comment]
That issue was fixed in a more recent version of the mod.

**Comment by TheRooster13** [comment]
This problem still exists (or has returned) in version 1.3.9. If you conquer a holy city that hasn't enhanced their religion, and there are no more religions available to found, and you have a prophet, and you choose to enhance the religion, you are taken to the screen to choose your symbol, but you cannot choose a symbol because all available religions are already taken. You are then stuck because you cannot continue to the next turn.
