### ISSUE TITLE
Event 'Icons of Our Past' issue

### ISSUE THREAD

**Issue by ieolus** [LoneGazebo/Community-Patch-DLL#1850]
Mod Version: 5/21

1. Mod List (if using standard CPP set, leave blank):
Standard CPP set w/ EUI

2. Type of error (i.e. crash, interface bug, AI quirk): 
Data error with event

3. Steps to reproduce:
Get 'Icons of Our Past' to fire

The choices for 'Icons of Our Past' don't seem correct.  When I looked into the SQL files I saw that the event 'CITY_EVENT_STONE_WORKS_DISCOVERY' was copied over from the previous event 'CITY_EVENT_MONUMENT_DEVELOPMENT' but not completed.  I think there is some mix-up in the event choices somewhere down the line.

 ('CITY_EVENT_MONUMENT_DEVELOPMENT','TXT_KEY_CITY_EVENT_MONUMENT_DEVELOPMENT','TXT_KEY_CITY_EVENT_MONUMENT_DEVELOPMENT_HELP',NULL,'AS2D_INTERFACE_BORDERS_EXPAND',20,1,'true','false','false',30,3,4,0,NULL,NULL,'ERA_MEDIEVAL','false','false',NULL,NULL,'false','false',NULL,NULL,'false',NULL,NULL,'false','BUILDINGCLASS_MONUMENT',NULL,'false','false',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'false','false','false','false','false','false','false','false','false','false','false','false','false','false',NULL,'false','false','false','false','false','false','false','false','false'),

 ('CITY_EVENT_STONE_WORKS_DISCOVERY','TXT_KEY_CITY_EVENT_MONUMENT_DEVELOPMENT','TXT_KEY_CITY_EVENT_MONUMENT_DEVELOPMENT_HELP',NULL,'AS2D_INTERFACE_BORDERS_EXPAND',25,1,'false','false','false',100,3,5,0,NULL,NULL,NULL,'false','false',NULL,NULL,'false','false',NULL,NULL,'false',NULL,NULL,'false',NULL,NULL,'false','false',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'RESOURCE_MARBLE','false','false','false','false','false','false','false','false','false','false','false','false','false','false','IMPROVEMENT_QUARRY','true','false','false','false','false','false','false','false','false'),

**Comment by Edaka** [comment]
Thanks for reporting. It's a known issue: #1791 . Let's keep it centered in that ticket.

**Comment by Edaka** [comment]
Oh yeah, it should be fixed in the latest beta. Which version are you on?

**Comment by ieolus** [comment]
Apologies for the duplicate issue.  I am on the latest (5/21) beta though, so maybe it isn't resolved.

**Comment by Edaka** [comment]
That's weird. I'm looking at the sql file right now and this is what I see: 
`('CITY_EVENT_STONE_WORKS_DISCOVERY','TXT_KEY_CITY_EVENT_STONE_WORKS_DISCOVERY','TXT_KEY_CITY_EVENT_STONE_WORKS_DISCOVERY_HELP',NULL,'AS2D_INTERFACE_BORDERS_EXPAND',25,1,'false','false','false',100,3,5,0,NULL,NULL,NULL,'false','false',NULL,NULL,'false','false',NULL,NULL,'false',NULL,NULL,'false',NULL,NULL,'false','false',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'RESOURCE_MARBLE','false','false','false','false','false','false','false','false','false','false','false','false','false','false','IMPROVEMENT_QUARRY','true','false','false','false','false','false','false','false','false'),`
Perhaps your version didn't install properly, iunno.
