### ISSUE TITLE
Incorrect dependency CP-43civs

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#3587]
_1. Mod version (i.e Date - 4/23):_10/17
_2. Mod list (if using Vox Populi only, leave blank):_ CP-only, with 43-civs dll
_3. Error description:_ The auto-installer install only (1) and (6c), but (6c) cannot be enabled since it depend on the non-existing "More Luxury". Either the dependency is wrong, either the auto-installer is wrong.
_4. Steps to reproduce (optional):_ Just install the CP-only 43-civs and try to play. You will see that (6c) : 
"Depends on Community Patch (v. 0-999)"
"Depends on (5) More Luxuries -CBO Edition (5-14b) (v. 0-999)"
"Reference More Luxuries (v. 0-999)"
The fact that it depends and reference more luxuries, with two deferent name for the same mod, is clearly fishy.

**Comment by LoneGazebo** [comment]
Fixed in the version I just released.

**Comment by MoiMagnus** [comment]
I just downloaded 10-17-1, and the problem is still here (maybe the link the first post 10/17 thread is the wrong one)

**Comment by LoneGazebo** [comment]
It still needs More Luxuries, just not both versions.

**Comment by MoiMagnus** [comment]
Is it normal that the auto-installer does not auto-instal it ?

**Comment by MoiMagnus** [comment]
And I've just re-download it and reinstall, and the modinfo still ask for both : 
`  <Dependencies>
    <Mod id="d1b6328c-ff44-4b0d-aad7-c657f83610cd" minversion="0" maxversion="999" title="Community Patch" />
    <Mod id="be2d13ee-d18d-410e-8f04-7cd19cd99a98" minversion="0" maxversion="999" title="(5) More Luxuries - CBO Edition (5-14b)" />
  </Dependencies>
  <References>
    <Mod id="be2d13ee-d18d-410e-8f04-7cd19cd99a98" minversion="0" maxversion="999" title="More Luxuries" />
  </References>`
Maybe I've misunderstood and I need to subscribe to the steam more luxury version, but I though that the auto-installer was supposed to instal everything needed.

**Comment by LoneGazebo** [comment]
The 43 CP must depend on it to function. If you intend to run it with just the CP, you need to delete the .modinfo dependencies (you can do so in a text editor).

**Comment by MoiMagnus** [comment]
Ok, I see. It works "better" with more luxuries.
(I think it should be precised in the auto-installer that you need More Luxuries from steam for this option)

It is probably bad luck, but each time I reinstall or start a new game, I have a different problem with this : 
+ Either I am not able to put more than 22 civs in a game (bad instal of the 43-civ dll)
+ Either the map fail to be generated (and I lose at the first turn because I have no units)
+ Either no ressources are generated on the maps (probably a bad instal of More Luxuries)
(Sometimes only bonus ressources within 2 tiles of the settler are generated, it is very strange)
=> If I manage to find a consistent bug, I will report it here, but if someone else than me could try to successfully intall CP 43-civ, it would help me to see if it is just successive bad luck with my install or a true problem.

**Comment by LoneGazebo** [comment]
I will test.

**Comment by LoneGazebo** [comment]
I have tested, works fine for me.

**Comment by MoiMagnus** [comment]
I still fail to have more than 22 civs in the game. 
(My install no longer have any problem if I select 22 civs or less). 
It seems to be a problem when generating the map (I play on Pangea). 
Is there any log of this ? Anything I could look at to see what's wrong with my install ?

**Comment by MoiMagnus** [comment]
I'm still failing to launch a game with 23 civs. 
Same scenario : I have no units, probably due to map generation failure.
(I was just doing some test runs with different CP settings, I am not really interested in playing 43-civ CP, so if it is a problem local to my computer, I don't really care and will go back to 43-civ VP, which works for me)

**Comment by LoneGazebo** [comment]
Very strange, works just perfect for me. Try this, though:

Uninstall/unsubscribe all other mods.
Install 43 civ CP.
In (6c), open (6c) 43 Cvis CP.modinfo

Delete this:

`<Mod id="be2d13ee-d18d-410e-8f04-7cd19cd99a98" minversion="0" maxversion="999" title="(5) More Luxuries - CBO Edition (5-14b)" />
  </Dependencies>
  <References>
    <Mod id="be2d13ee-d18d-410e-8f04-7cd19cd99a98" minversion="0" maxversion="999" title="More Luxuries" />
  </References>`

Save the file.

Load the game.

**Comment by MoiMagnus** [comment]
It work well without problems. I've tried revert the change in the .modinfo and subscribing back to More Luxuries and it failed again, so my problem is only when I have both More Luxuries and more than 23 civs.

(Note that with More Luxuries, I don't always have a faillure to generate the map. Sometimes, the game start but with almost no ressources on the map, only 2 bonus ressource around each settler, and no city states)

**Comment by LoneGazebo** [comment]
If you are trying to do CP 43 + More Luxuries, you need to use the More Luxuries from VP and, this gets tricky, the AssignStartingPlots from the EUI or No-EUI folders in the 'full' version of the 43civ CP.

G

**Comment by MoiMagnus** [comment]
In addition to what you said, I also needed to delete the dependency of VP's More Luxuries on CBO.
But then it worked !
Thank you.

However, for some obvious reasons, the auto-installer has to be changed in upcomming version (either by deleting the dependency to More Luxuries, either by installing More Luxuries properly, but current state is not user friendly)

**Comment by LoneGazebo** [comment]
Well, not necessarily - your choice of installation is not an 'out of the box' installation type. The 43 civ DLL 6c is designed to either be _just_ CP or VP w or w/o EUI. I cannot account for all variations (especially since CP + More Luxuries needs a special copy of the AssignStartingPlots code.

**Comment by LoneGazebo** [comment]
Glad you got it to work, though.

**Comment by MoiMagnus** [comment]
@LoneGazebo I understand what your saying, but currently, the auto-installer has an option which does not work : 
If you select "Community Patch only, 43-civ", you CANNOT play out of the box. You either need to delete the dependency on More Luxuries, either need to make this complex procedure. I have no problems with CP+More Luxuries+43civs being diffucult to install as long as CP+43civs works without modifications, which is not currently the case.

**Comment by LoneGazebo** [comment]
Right, yes, that's a given- I thought you were talking about adding another dependency.

G
