### ISSUE TITLE
EUI doesn't preview bonuses from various policies

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#408]
![8930_2015-07-08_00006](https://cloud.githubusercontent.com/assets/1131228/8564180/64f79734-2562-11e5-9ea5-70c7af43b100.png)
![8930_2015-07-08_00007](https://cloud.githubusercontent.com/assets/1131228/8564181/6df6b0ae-2562-11e5-9962-6ce62516828d.png)
Exploitation being the one example.
Also it doesn't preview Imperialism finisher bonus and Scientific Revolution from Rationalism.
And clear marsh/chop the jungles and jungle lumbermill.
![8930_2015-07-08_00011](https://cloud.githubusercontent.com/assets/1131228/8564361/8924a5a0-2564-11e5-9c68-19bba8a232c1.png)

**Comment by LoneGazebo** [comment]
I've implemented the ones that are feasible (and fit in EUI's system).

G

**Comment by Radost** [comment]
I remember EUI previewed old piety and rationalism bonuses just fine, though it was just saying Piety and Rationalism in the preview.
And Imperialism finisher still doesn't show up.

**Comment by LoneGazebo** [comment]
Plot based yield mods won't work, as EUI's tooltip manager can't handle them without applying the effects to all plots (i.e. imperialism finisher).

G
