### ISSUE TITLE
Combat Preview Health Meter Incorrect Display

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5354]
_1. Mod version (i.e Date - 4/23): February 17th (4.2.17)​

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: In this certain scenario the health meter preview should indicate that the health of the enemy Cruiser will be completely depleted on hit and the health of the enemy has only 13 HP but in preview appears to have much more than that.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![Civ5Screen0001](https://user-images.githubusercontent.com/49090452/57571151-ec0cb580-7412-11e9-929e-e32f457df902.png)

**Comment by Edaka** [comment]
This is a weird interaction between the combat preview and raised maximum HP provided by the dreadnought promotion line.

**Comment by Aqinu** [comment]
And I wanted to ask if it is worth to post issues regarding wrong descriptions or incomplete descriptions from Civiliopedia or other places

**Comment by TechpriestEnginseer** [comment]
post it, whatever makes things better.

**Comment by LoneGazebo** [comment]
This has been fixed since feb.

**Comment by Edaka** [comment]
I'm still experiencing this on 4/20, though. Will attach screenshots later, if needed.

**Comment by Edaka** [comment]
So, this is version 4/20. I'm attacking with my Dreadnought ship a Boarding Party ship, so they have different max HP. As you can see, my ship is supposed to deal 35 HP damage to the enemy ship, which has only 34 HP left, killing it. That isn't reflected in the combat preview HP meter.
![image](https://user-images.githubusercontent.com/12978597/57772467-27aec480-771e-11e9-8fe9-e334f201c9d9.png)

Attacking the same enemy ship with a different ship that also has Boarding Party, therefore standard max HP, the combat preview health meter is correct.
![image](https://user-images.githubusercontent.com/12978597/57772637-9724b400-771e-11e9-9e57-7a070fa2ae62.png)

These show the inaccuracies when attacking a Boarding Party ship with a Dreadnought, but they also exist the other way around.

**Comment by Aqinu** [comment]
Better post the previous comment from above of this one as a new issues (remember to specify the version) so that the owner will have a greater chance of seeing your post and solve the issue
