### ISSUE TITLE
Unable to load textures

### ISSUE THREAD

**Issue by Erubadhronn** [LoneGazebo/Community-Patch-DLL#7995]
_1. Mod version (i.e Date - 4/14):_
5/12/2020 Vox Populi inc EUI

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Unable to load textures as follows:
DC45_DiplomacyOverview.dds
DC45_AdvisorCOunsel.dds
DC45_Greatwork.dds
DC45_Culture.dds
DC45_EspionageOverview.dds
TopPanelGoldenAge.dds
MenuButton.dds
HelpButton.dds

_4. Steps to reproduce (optional):_
All I do is start Civ V, click mods, select the cbp mods, start game and during the loading the error messages show up one after the other.

If needed I can provide screenshots of the error messages but there isnt much to show except the text "Unable to load texture DC45_DiplomacyOverview.dds... etc for each one.

I've got an extensive mod list that I use, but I've tested each one individually with the CBP when it worked and had no clashes.

I've tested with and without extra mods and get the same messages. 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Typically a result of the ui_bc1 folder not ending up in your civ directory. Check your civ default directory.

**Comment by Erubadhronn** [comment]
cheers.

Do you mean the steam directory or the my games folder? also how do I fix that? where might I find the ui_bc1 folder in order to put it in the correct place

**Comment by LoneGazebo** [comment]
It needs to end up in your DLC folder.

**Comment by Erubadhronn** [comment]
I cant seem to find ui_bc1 anywhere in either my games or in the steam directory. 

I used the automatic installer. Maybe I should uninstall and try manual installation?

**Comment by Vyyt02** [comment]
Run a search for the ui_bc1 folder on your drive C: When you find it, move it to the DLC folder of your Civ5 install. This should fix it for you even for future VP updates (until there's a new EUI version, then you will have to repeat this again, because your EUI will be outdated)

**Comment by Flame-zombie** [comment]
> It needs to end up in your DLC folder.

I have the same issue here, but the UI_bc1 IS in my DLC folder. Issue still occurs unless I disable the compatibility patch (which comes with many more issues). Could it be because my Civ is installed to a different drive than my documents folder?

**Comment by WhoStoleMyPants** [comment]
I have the exact same issue and ui_bc1 is also in the DLC folder like the others. First time attempting to use Vox Populi mods. Civ V is installed to a separate drive with all Steam games, but writes (annoyingly) to the Documents folder on my OS drive. I used the auto-installer for 7-1-3, but had to correct the install directory from my administrator profile's User folder to my everyday profile where all my games are. I've only ever installed Vox Populi, so no conflicting modifications.
