### ISSUE TITLE
where is all this food coming from

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#906]
![image](https://cloud.githubusercontent.com/assets/1358966/11715321/3f608f36-9f41-11e5-900b-2f01104d2da8.png)

it says 28 from terrain, i'm counting 13 ...

**Comment by Heinous-Hat** [comment]
Ignoring the EUI colored overlay (which doesn't look right), I count 22f from tiles worked by 13 citizens.

**Comment by LoneGazebo** [comment]
If you walk the dll through the yield stuff in city.cpp, do the numbers match up?

**Comment by LoneGazebo** [comment]
Oh, hey, another random question (can't find inca thread for some reason) - do mountains still create city connections for the inca?

G

**Comment by LoneGazebo** [comment]
Oh, also also, any pathfinder quirks remaining, i.e. ranged units moving up to shoot?

**Comment by ilteroi** [comment]
i updated the description for the inca already, so that should be fine. i made it so that everybody can enter mountain plots with cities or routes. but only the inca can build them.

ranged attack is fixed, only known bug at the moment concerns the airstrikes.

but please, go ahead and test. in fact, that should be the release recommendation: play with or against the inca :)

**Comment by LoneGazebo** [comment]
Cool. Testing the inca reveals that some mountains were still unable to be settled on, but I fixed it. City graphics don't show until size 5-15 (depending on mountain type/shape), which is okay, but not great. We'll see how the community likes it. I wonder if we could force Machu Pichu graphics to appear for inca cities being settled? That'd be neat. 

So if the Inca settle a city, but connects no roads to it, no one can get to it?

I'll take a look at air strikes as well.
G
